In [1]:
from yieldCurvePrediction import yieldCurvePredictor
from CIRModel import BasicCIRModel
from ECIR_new import ECIRModel
import pandas as pd

In [2]:
# Load the DGS_30 data
dgs_30_data = pd.read_csv('Data Folder/DGS_30.csv')
# Load the DGS3MO data
dgs3mo_data = pd.read_csv('Data Folder/DGS3MO.csv')

# Convert the 'DATE' column to datetime and set it as index for both DataFrames
dgs_30_data.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)
dgs_30_data['Date'] = pd.to_datetime(dgs_30_data['Date'])
dgs_30_data.set_index('Date', inplace=True)

dgs3mo_data.rename(columns={'DATE': 'Date'}, inplace=True)
dgs3mo_data['Date'] = pd.to_datetime(dgs3mo_data['Date'])
dgs3mo_data.set_index('Date', inplace=True)

# Insert the DGS3MO data into the DGS_30 data as the first column
dgs_30_data.insert(0, 'DGS3MO', dgs3mo_data['DGS3MO'])

data=dgs_30_data

dates = data.loc[data.index >= '2024-03-15'].index

params_ecir = {
    "kappa": 0.01227,    
    "mu_r": 0.09854,     
    "sigma": 0.09395,    
    "mu": 0.002995,      
    "gamma": 0.002321,   
    "r": 66,             
    "p": 0.3049          
}

params_cir = {
    "kappa": 1.2310,
    "mu_r": 0.0459,
    "sigma": 0.1410
}

In [3]:
cir = yieldCurvePredictor(BasicCIRModel(**params_cir), dates[0], data)
ecir = yieldCurvePredictor(ECIRModel(**params_ecir), dates[0], data)

In [4]:
cir.comb_data()[1]

        Actual Prices  Simulated Prices
DGS3MO     987.008875        987.060139
DGS1       953.356762        953.539875
DGS2       912.389692        912.783614
DGS3       873.063126        873.531506
DGS4       834.948001        835.387381
DGS5       798.082541        798.467487
DGS6       762.557386        762.883882
DGS7       728.516818        728.789045
DGS8       696.049752        696.307629
DGS9       665.071079        665.292910
DGS10      635.465274        635.663922
DGS11      607.136573        607.323345
DGS12      580.030096        580.189106
DGS13      554.101031        554.254070
DGS14      529.305516        529.447394
DGS15      505.600682        505.734643
DGS16      482.944680        483.075346
DGS17      461.296707        461.409484
DGS18      440.617032        440.727075
DGS19      420.867009        420.965352
DGS20      402.009092        402.109563
DGS21      384.006844        384.104435
DGS22      366.824939        366.915227
DGS23      350.429166        350.509745
DGS24      334.786425        334.861265
DGS25      319.864722        319.930069
DGS26      305.633160        305.691831
DGS27      292.061928        292.115766
DGS28      279.122287        279.164988
DGS29      266.786555        266.820276
DGS30      255.028087        255.051021

In [5]:
ecir.comb_data()[1]

        Actual Prices  Simulated Prices
DGS3MO     986.734888        985.506599
DGS1       951.709539        947.649598
DGS2       911.209084        901.657147
DGS3       874.932213        865.061893
DGS4       840.937548        826.702946
DGS5       808.079166        795.543414
DGS6       775.942037        756.127320
DGS7       745.232609        729.432684
DGS8       717.026255        695.580326
DGS9       691.241153        668.020924
DGS10      667.335093        650.200743
DGS11      644.760451        627.835354
DGS12      623.325199        601.131012
DGS13      602.954346        579.453545
DGS14      583.594017        561.217569
DGS15      565.206795        533.855202
DGS16      547.767806        528.537689
DGS17      531.261510        509.393412
DGS18      515.679167        489.822626
DGS19      501.016904        479.816535
DGS20      487.274305        463.682444
DGS21      474.453466        457.786060
DGS22      462.558422        445.624735
DGS23      451.594900        430.657764
DGS24      441.570327        417.562625
DGS25      432.494052        417.334509
DGS26      424.377753        403.107062
DGS27      417.235994        394.541967
DGS28      411.086923        390.393823
DGS29      405.953109        377.328521
DGS30      401.862516        381.224876